---
- name: Install php-fpm 8.1
  hosts: ubuntu
  become: yes

  tasks:
    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 8.1"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 8.1
      apt: name=php8.1 state=present
